### ISSUE TITLE
FrequentItems IllegalArgumentException

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#175]
Still working on the repo, but we recently saw this in our logs:
```
java.lang.IllegalArgumentException: reqOffset: 4, reqLength: , (reqOff + reqLen): 1413567575, allocSize: 480
  at com.yahoo.memory.UnsafeUtil.checkBounds(UnsafeUtil.java:156)
  at com.yahoo.sketches.ArrayOfStringsSerDe.deserializeFromMemory(ArrayOfStringsSerDe.java:54)
  at com.yahoo.sketches.ArrayOfStringsSerDe.deserializeFromMemory(ArrayOfStringsSerDe.java:23)
  at com.yahoo.sketches.frequencies.ItemsSketch.getInstance(ItemsSketch.java:263)
```

Posting here in case someone might know just from the message what might be going wrong.

**Comment by leerho** [comment]
There is too little information here to diagnose exactly what is going on.  However, based on prior experience, it is most likely a corruption of the Memory object being passed to the Array of Strings serDe.  This corruption most likely occurs at the systems level as the binary image is being encoded and decoded as it is passed between systems or to / from storage.

**Comment by leerho** [comment]
Without any further information, I am going to close this issue.
