### ISSUE TITLE
DoublesUnion serde issue

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#195]
Stacktrace:
```
java.lang.AssertionError: reqOffset: 8, reqLength: 8, (reqOff + reqLen): 16, allocSize: 8
	at com.yahoo.memory.UnsafeUtil.assertBounds(UnsafeUtil.java:141)
	at com.yahoo.memory.WritableMemoryImpl.getLong(WritableMemoryImpl.java:250)
	at com.yahoo.sketches.quantiles.DoublesUnionImpl.heapifyInstance(DoublesUnionImpl.java:80)
	at com.yahoo.sketches.quantiles.DoublesUnionBuilder.heapify(DoublesUnionBuilder.java:87)
```

Repro:
```
        DoublesUnion union = DoublesUnion.builder().build();
        DoublesUnionBuilder.heapify(Memory.wrap(union.toByteArray()));
```

**Comment by leerho** [comment]
Thank you for finding this.  This will be fixed in the next minor release.
