### ISSUE TITLE
NULL handling in Quantiles sketch

### ISSUE THREAD

**Issue by kkalyan** [DataSketches/sketches-core#239]
If the input data contains NULL values, Quantiles is throwing NP exception.

```
$ cat data.json
{"value": 1, "category": "a"}
{"value": 2, "category": "a"}
{"value": null, "category": "a"}

$ cat test.pig
register memory-0.11.0.jar;
register sketches-core-0.11.1.jar;
register sketches-pig-0.11.0.jar;

define dataToSketch com.yahoo.sketches.pig.quantiles.DataToDoublesSketch();
--a = load 'data.txt' as (value:double, category);
a = load 'data.json' Using JsonLoader('value:double, category: chararray');
b = group a by category;
c = foreach b generate flatten(group) as (category), flatten(dataToSketch(a.value)) as sketch;
dump c;

$ pig -x local test.pig 

...
2019-02-05 19:38:49,748 [Thread-24] WARN  org.apache.hadoop.mapred.LocalJobRunner - job_local_0001
org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: b: Local Rearrange[tuple]{chararray}(false) - scope-37 Operator Key: scope-37): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(com.yahoo.sketches.pig.quantiles.DataToDoublesSketch$IntermediateFinal)[tuple] - scope-28 Operator Key: scope-28) children: null at []]: java.lang.NullPointerException
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigCombiner$Combine.processOnePackageOutput(PigCombiner.java:198)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigCombiner$Combine.reduce(PigCombiner.java:176)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigCombiner$Combine.reduce(PigCombiner.java:52)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:176)
	at org.apache.hadoop.mapred.Task$NewCombinerRunner.combine(Task.java:1502)
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.sortAndSpill(MapTask.java:1436)
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.flush(MapTask.java:1298)
	at org.apache.hadoop.mapred.MapTask$NewOutputCollector.close(MapTask.java:699)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:766)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing [POUserFunc (Name: POUserFunc(com.yahoo.sketches.pig.quantiles.DataToDoublesSketch$IntermediateFinal)[tuple] - scope-28 Operator Key: scope-28) children: null at []]: java.lang.NullPointerException
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:364)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.yahoo.sketches.pig.quantiles.DataToDoublesSketch$IntermediateFinal.exec(DataToDoublesSketch.java:320)
	at com.yahoo.sketches.pig.quantiles.DataToDoublesSketch$IntermediateFinal.exec(DataToDoublesSketch.java:269)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextTuple(POUserFunc.java:365)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:359)
	... 15 more
Input(s):
Failed to read data from "data.json"

Output(s):
Failed to produce result in "file:/tmp/temp-120668530/tmp-2117801155"
```

**Comment by kkalyan** [comment]
looks like this is already addressed https://github.com/DataSketches/sketches-pig/pull/50 closing.
