### ISSUE TITLE
could not access class in package 'sun.misc'

### ISSUE THREAD

**Issue by tangzk** [DataSketches/sketches-core#44]
I used sketch-core in an hadoop-style enviorment with QuantileSketch and Memory class, but encountered the following problem. Because of the security policy of the platform, the librabry couldn't used. please help me!
```
Caused by: java.lang.RuntimeException: Unable to acquire Unsafe. 
	at com.yahoo.sketches.memory.UnsafeUtil.<clinit>(UnsafeUtil.java:105)
	... 5 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.alibaba.apsara.sandking.SandboxSecurityManager.checkPermission(SandboxSecurityManager.java:354)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at com.alibaba.apsara.sandking.SandboxLauncher$AppClassLoader.loadClass(SandboxLauncher.java:247)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yahoo.sketches.memory.UnsafeUtil.<clinit>(UnsafeUtil.java:68)
	... 5 more
```

**Comment by leerho** [comment]
Your system is injecting its own "SandboxLauncher" class loader which is causing your problem.
Restricting access to the Java Unsafe class by your system is misguided as Unsafe is no less secure than any program using native methods with JNI.  There are many high-performance systems including Kafka and others that depend on Unsafe for high performance.  Unsafe, in turn, uses JNI to access underlying C/C++ methods and there are millions of programs that rely on JNI for the same reason.   Hadoop itself relies heavily on JNI for performance reasons.  

In the JDK9/10 time frame I will likely deprecate the use of Unsafe and move to JNI and native access methods.  But I cannot speak to any timelines yet.

I suggest you talk to your system admin folks.

**Comment by tangzk** [comment]
Thank you for your response. 
I have used the QuantileSketch in a mapreduce-style enviorment. The platform supports us to write a hive udf to process large scale data. Yet It also restricted the code of udf in the safe sanbox. That was my problem.
My current solution is to rewrite the NativeMemory dependency in QuantileSketch class to support ordinary java-object memory usage. But I think the good design is to extract the NativeMemory class from the Sketch, and to support various Memory type.

**Comment by leerho** [comment]
If you do this, would you consider submitting it back as a PR?
